### ISSUE TITLE
Icons - add missing sizing tokens

### ISSUE THREAD

**Issue by larserbach** [deven-org/B01LER-Kitchen#241]
**Requirements**
- #181 needs to be done first
- #242 needs to be done first

**ACs:** 
- [x] Design Task: Apply newly added tokens on components.
- [x] Dev Task: Apply newly added tokens on components.
- [x] Every icon in every component has a dimension token and a config token applied.

**Comment by thrbnhrtmnn** [comment]
Closed as complete
