### ISSUE TITLE
Review all components and add missing tokens (ideally on a single branch)

### ISSUE THREAD

**Issue by m-nti** [deven-org/B01LER-Kitchen#242]
Tokens which decribe the size of the icons. 
- [x]  Create token of type `sizing`
- [x] Naming should follow this example: Forms.Caption.Icon.**Sizing**

Tokens which decribe the variant of the icon. 
- [x]  Create token of type `componentConfig`
- [x] Naming should follow this example: Forms.Caption.Icon.**IconSize**

**Comment by thrbnhrtmnn** [comment]
Closed as complete
