### ISSUE TITLE
Slider - Implement Tooltip

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/B01LER-Kitchen#292]
**Story**

We want to add the Tooltip component to the Slide, so it is aligned to the design.

**Pre-requisites:** 

- [x] Tooltip user story is closed (#118)
- [ ] Tooltip refactoring is done (#461)

**Acceptance criteria:** 

- [ ]  If the user hovers or presses the thumb, they get presented with a popover, displaying the value
- [ ] In case props were changed: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

**Comment by thrbnhrtmnn** [comment]
Ticket will be done within #268, this task is not needed anymore
