### ISSUE TITLE
Storybook Documentation - Component: Checkbox

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/B01LER-Kitchen#409]
### Description / User Story

With this task we want to make the Checkbox Component Docs page in Storybook look like the [template](https://www.figma.com/file/Sg2Uox6PchuAsMKY4ShXku/StorybookTemplate?type=design&node-id=1-1072&mode=design&t=LeRpJsk2yo3q8jHL-0) from design.

---

### Acceptance Criteria

- [x] Component Page has the same structure as the design template (in the following order):
    - [x]  Headline & Intro Text incl. a list of anchor links to all following sections
    - [x]  Docs Area with Example and all Props (see which props should be displayed for this component in the section below)
    - [x]  Appearance
      - [x] SizeVariant (incl. sizes = SM, MD, LG)
    - [x] Content / Settings
      - [x]  Unchecked
      - [x]  Checked
      - [x]  Indeterminate
    - [x]  States
        - [x] Disabled  (incl. disabled = true)
        - [x] Readonly  (incl. readonly = true)
    - [ ]  Validation
      - [ ] Required  (incl. required = true)
      - [x] hasError  (incl. hasError = true, once submitted)
    - [x] Dependencies
        - [x]  FormCaptionGroup
            - A checkbox with a hint
            - A checkbox with an error (hasError = true) and all captions (hint text and error message)
            - A checkbox with an error (hasError = true) and a hint text only
            - A checkbox with an error (hasError = true) and an error message only
        - [x]  Label
            - A checkbox with a label
            - A checkbox with no label
- [x]  Component Page includes the texts as defined in the section below
- [x]  Component Page text styles (uppercase, lowercase, spacing) correspond the the design template
- [x]  Component Page spacing corresponds to design template
- [x]  Component Page colors correspond to design template

---

### Props
See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Checkbox" for all props that should be displayed for the component, incl. their description, default values and the type of controls.

If the props in the list are not the same as the component currently uses, just leave a comment in column G in the excel and a follow-up task will be created. Fixing the components is not part of this ticket.

As a part of this user story, the research is necessary to see if it is possible to have multiple conditional controls. In particular, to show the control for 'errorMessage' and 'errorIcon' only if ‘hasError’ AND ‘hasLabel’ are both true. In case this is not possible, please comment in the ticket and create a condition where when 'hasError' is true, errorMessage and errorIcon controls become visible.

---

### Content / Texts

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Documentation Texts" for all texts that should be displayed for the component. Filter column A in cell A3 to only show you the texts of this components.

For the texts please change "[component name]" with "Checkbox".

Also all the examples in the documentation below the Props should not use the default values, but they should use descriptive texts for Label, Placeholder and other text fields. Some examples are already given in the template.

---

### Background information

- Example of a collapsible Props Section can be seen [here](https://www.kickstartds.com/storybook/?path=/docs/base-button--solid)

**Comment by thrbnhrtmnn** [comment]
Feedback / Open points @JpunktWpunkt : 

- [ ] Checked: Please change headline of the section form "Checked / Unchecked" to "Checked", as this section is only about the checked prop and there is no unchecked prop.
- [ ] Has Error: change "...was set as required and has not been filled..." to "...was set as required and has not been checked..."
- [ ] Form Label: The example without a label should not just have an empty label, but hasLabel should be false

**Comment by thrbnhrtmnn** [comment]
Approved the PR, everything looks nice!
