### ISSUE TITLE
Storybook Documentation - Component: Radio Group

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/B01LER-Kitchen#413]
### Description / User Story

With this task we want to make the Radio Group Component Docs page in Storybook look like the [template](https://www.figma.com/file/Sg2Uox6PchuAsMKY4ShXku/StorybookTemplate?type=design&node-id=1-1072&mode=design&t=LeRpJsk2yo3q8jHL-0) from design.

---

### Acceptance Criteria

- [ ] Component Page has the same structure as the design template (in the following order):
    - [ ]  Headline & Intro Text incl. a list of anchor links to all following sections
    - [ ]  Docs Area with Example and all Props (see which props should be displayed for this component in the section below)
    - [ ]  Appearance
      - [ ] SizeVariant (incl. sizes = SM, MD, LG)
      - [ ] Direction(incl. horizontal and vertical)
    - [ ] Content / Settings
      - [ ]  Legend
      - [ ] Without Legend
    - [ ]  States
        - [ ] Default
        - [ ] Disabled  (incl. disabled = true)
        - [ ] Readonly  (incl. readonly = true)
    - [ ]  Validation
      - [ ] Required
      - [ ] hasError  (incl. hasError = true, once submitted)
    - [ ] Dependencies
        - [ ]  FormCaptionGroup
            - A radio group with all captions (hint text and error message)
            - A radio group with a hint
            - A radio group with an error (hasError = true) and a hint text only
            - A radio group with no captions
- [ ]  Component Page includes the texts as defined in the section below
- [ ]  Component Page text styles (uppercase, lowercase, spacing) correspond the the design template
- [ ]  Component Page spacing corresponds to design template
- [ ]  Component Page colors correspond to design template

---

### Props
See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "RadioGroup" for all props that should be displayed for the component, incl. their description, default values and the type of controls.

If the props in the list are not the same as the component currently uses, just leave a comment in column G in the excel and a follow-up task will be created. Fixing the components is not part of this ticket.

---

### Content / Texts

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Documentation Texts" for all texts that should be displayed for the component. Filter column A in cell A3 to only show you the texts of this components.

For the texts please change "[component name]" with "Radio Group".

Also all the examples in the documentation below the Props should not use the default values, but they should use descriptive texts for Label, Placeholder and other text fields. Some examples are already given in the template.

---

### Background information

- Example of a collapsible Props Section can be seen [here](https://www.kickstartds.com/storybook/?path=/docs/base-button--solid)

**Comment by thrbnhrtmnn** [comment]
Feedback @bar-tay :

- [ ] Headline: Please rename the page to "Radio Group", please also move it into a folder called "Radio Group" together with the the "Radio" Component. In the end it should be similar to how the current Tooltip is structured on develop, where both the Tooltip as well as the Tooltip Bubble are placed inside the Tooltip Folder.
- [ ] Props Panel: Default for errorMessageIcon should be "undefined"
- [ ] SizeVariant: Change text from "The Radio component..." to "The Radio Group component..."
- [ ] Direction: Remove second "." at the end of the text and also remove or comment-out the whole section as long as there is no direction or layout prop that works
- [ ] Required: Change text from "...was not filled, before..." to "...was not checked, before..."
- [ ] Has Error: Text is wrong, please use the correct text from the Excel.
- [ ] Has Error: Please do not include an error message and an error message icon in the example, just show the error state.
- [ ] TOC: Following Links are not working or linking to the correct content:
   - [ ] Appearance (Headline in section below is missing written wrong)
   - [ ] Direction (same link as in Size Variant) > remove this, if you removed the section

**Comment by thrbnhrtmnn** [comment]
@bar-tay Thanks for the changes. There is only one small thing left:
- [ ] Radio and Radio Group are now correctly placed in a folder, but it is named "Radio" and not "Radio Group"

**Comment by thrbnhrtmnn** [comment]
Looks good, once merged the issue can be closed
