### ISSUE TITLE
Storybook Documentation - Component: Button Group

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/B01LER-Kitchen#416]
#### Description / User Story

With this task we want to make the Button Group Component page in Storybook look like the [template](https://www.figma.com/file/Sg2Uox6PchuAsMKY4ShXku/StorybookTemplate?type=design&node-id=1-1072&mode=design&t=qJ4f7V5skw35QEXC-0) from design.

----
#### Acceptance Criteria
- [x] Component Page has the same structure as the design template (in the following order):
   - [x] Headline & Intro Text incl. a list of anchor links to all following sections
   - [x] Docs Area with Example and all Props (see which props should be displayed for this component in the section below)
   - [x] Appearance
      - [x] Alignment (incl. alignment = left, center, right)
- [x] Component Page includes the texts as defined in the section below (incl. non default values for the shown examples)
- [x] Component Page text styles (uppercase, lowercase, spacing) correspond the the design template
- [x] Component Page spacing corresponds to design template
- [x] Component Page colors correspond to design template
- [x] The first example should have a combination of text buttons and icon buttons, instead of two examples containing text buttons separately, and below that, icon buttons separately. In addition, texts "Text-Buttons" and "Icon-Buttons" should be removed.

----
#### Props

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Button Group" for all props that should be displayed for the component, incl. their description, default values and the type of controls. Props that do not appear and that can be removed, should also be removed (not including theme for example, because this is needed for all components, but still not part of the props section).

If the props in the list are not the same as the component currently uses, just leave a comment in column G in the excel and a follow-up task will be created. Fixing the components is not part of this ticket.

----
#### Content / Texts

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Documentation Texts" for all texts that should be displayed for the component. Filter column A in cell A3 to only show you the texts of this components.

For the texts please change "[component name]" with "Button Group" and "[componentName]" with "buttonGroup".

Also all the examples in the documentation below the Props should not use the default values, but they should use descriptive texts for Label, Placeholder and other text fields. Some examples are already given in the template.

----
#### Background information
- Example of a collapsible Props Section can be seen [here](https://www.kickstartds.com/storybook/?path=/docs/base-button--solid)

**Comment by bar-tay** [comment]
Currently the Itemspacimg from Buttongroup token only gives back  these two different sizes : { XS: '4px', SM: '4px', MD: '8px', LG: '8px', XL: '8px' } which is why the size prop only changes the component between these two values

**Comment by thrbnhrtmnn** [comment]
Hey @bar-tay , almost there, I would like to change a few minor things still:

- [ ] Please change the icon button from secondary to silent in the default story and in all examples
- [ ] Please remove the texts above each button group in the alignment story
- [ ] The alignment prop in the default story does not do anything, can this be fixed?
