### ISSUE TITLE
Storybook Documentation - Component: Toggle Switch

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/B01LER-Kitchen#419]
### Description / User Story

With this task we want to make the Toggle Switch Component Docs page in Storybook look like the [template](https://www.figma.com/file/Sg2Uox6PchuAsMKY4ShXku/StorybookTemplate?type=design&node-id=1-1072&mode=design&t=LeRpJsk2yo3q8jHL-0) from design.

---

### Acceptance Criteria

- [x] Component Page has the same structure as the design template (in the following order):
    - [x]  Headline & Intro Text incl. a list of anchor links to all following sections
    - [x]  Docs Area with Example and all Props (see which props should be displayed for this component in the section below)
    - [x]  Appearance
      - [x] SizeVariant (incl. sizes = SM, MD, LG)
      - [ ] ControlPosition
        - Control: Left
        - Control: Right
    - [x] Content / Settings
      - [x]  Active
      - [x]  Inactive
      - [x] OnLabel
      - [x] OffLabel
    - [x]  States
        - [x] Disabled  (incl. disabled = true)
        - [ ] Readonly  (incl. readonly = true)
    - [x] Dependencies
        - [ ]  FormLabel
          - A Toggle Switch with a label
          - A Toggle Switch with no label
        - [x]  FormCaption
            - A Toggle Switch with a hint
- [x]  Component Page includes the texts as defined in the section below
- [x]  Component Page text styles (uppercase, lowercase, spacing) correspond the the design template
- [x]  Component Page spacing corresponds to design template
- [x]  Component Page colors correspond to design template

---

### Props
See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Checkbox" for all props that should be displayed for the component, incl. their description, default values and the type of controls.

If the props in the list are not the same as the component currently uses, just leave a comment in column G in the excel and a follow-up task will be created. Fixing the components is not part of this ticket.

---

### Content / Texts

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Documentation Texts" for all texts that should be displayed for the component. Filter column A in cell A3 to only show you the texts of this components.

For the texts please change "[component name]" with "Toggle Switch".

Also all the examples in the documentation below the Props should not use the default values, but they should use descriptive texts for Label, Placeholder and other text fields. Some examples are already given in the template.

---

### Background information

- Example of a collapsible Props Section can be seen [here](https://www.kickstartds.com/storybook/?path=/docs/base-button--solid)

- This user story relates to #517

**Comment by JpunktWpunkt** [comment]
[feature/419-storybook-toggle-switch](https://github.com/deven-org/B01LER-Kitchen/tree/feature/419-storybook-toggle-switch)

**Comment by thrbnhrtmnn** [comment]
Continued Review:

- [ ] Active: Please change headline to "Checked"
- [ ] Active: Please add labels to the examples named "Active" and "Inactive"
- [ ] Active: Please add another example with the props: variant=leading, showStateLabel=true, checked=true, label="Active and Inactive state labels", onLabel="Active", offLabel="Inactive"
- [ ] OnLabel: Please change headline to "On Label"
- [ ] OnLabel: In the example please change the variant to "leading", the label to "With on label", onLabel to "On", offLabel to "Off", showStateLabel to "true" and checked to "true"
- [ ] OffLabel: Please change headline to "Off Label"
- [ ] Off Label: In the example please change the variant to "leading", the label to "With off label", onLabel to "On", offLabel to "Off", showStateLabel to "true" and checked to "false"
- [ ] States: Please remove "The error state is documented under validation [link to Validation]."
- [ ] Disabled: Please use default ToggleSwitch in the example with: variant=trailing, label="Disabled", showStateLabel=true and disabled=true
- [ ] Disabled: Please add another example with the props: disabled=true, variant=leading, showStateLabel=true, label="Disabled with state label", onLabel="On Disabled", offLabel="Off Disabled"
- [ ] Readonly: Please use default ToggleSwitch in the example with: variant=trailing, label="Readonly", showStateLabel=true and readonly=true
- [ ] Readonly: Please add another example with the props: readonly=true, variant=leading, showStateLabel=true, label="Readonly with state label", onLabel="On Readonly", offLabel="Off Readonly"
- [ ] FormLabel: Please remove Form Label section, as the component is not using the Form Label
- [ ] FormCaption: Please change link and link-name to Form Caption
- [ ] FormCaption: Please change examples to the following:
   - [ ] 1. Example with the props: variant=trailing showStateLabel=true, label="Hint message", hasHint=true, hintMessage="This is a small hint message", hintIcon=blrInfo
   - [ ] 2. Example with the props: variant=leading, showStateLabel=true, label="Hint message with state label", onLabel="On", offLabel="Off", hasHint=true, hintMessage="This is a small hint message", hintIcon=blrInfo

**Comment by thrbnhrtmnn** [comment]
Feedback @JpunktWpunkt :
- [ ] TOC: Links to "On Label" and "Off Label" still do not work
- [ ] TOC: Please also remove Form Label from TOC
- [ ] Props: offLabel is currently shown when variant=trailing, please change this so offLabel is only shown when variant=leading
- [ ] FormCaption: The second example misses the onLabel "On" and offLabel "Off"
