### ISSUE TITLE
TextInput - rename tokens

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#541]
#### Description / User Story

After changing the structure of the component tokens within #239 , we now need to adjust the token names for the TextInput.

----
#### Acceptance Criteria
- [ ] Design: All tokens used in the TextInput are following the new token naming
- [ ] Dev: All tokens used in the TextInput are following the new token naming

----
#### Background information
- [Link](https://www.figma.com/file/C4vgEKz8mKyulJ4gm3Qdql/%F0%9F%AB%A7-%5BBLR%5D-The-B01LER?type=design&node-id=8035%3A7817&mode=design&t=eTH1Q2XmAvBy562Q-1) to new token naming documentation
- #357 should be done for this component in parallel

**Comment by larserbach** [comment]
Decided together with @ChristianHoffmannS2: No task here
