### ISSUE TITLE
FormCaption - rename tokens

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#544]
#### Description / User Story

After changing the structure of the component tokens within #239 , we now need to adjust the token names for the FormCaption.

----
#### Acceptance Criteria
- [ ] Design: All tokens used in the FormCaption are following the new token naming
- [ ] Dev: All tokens used in the FormCaption are following the new token naming

----
#### Background information
- [Link](https://www.figma.com/file/C4vgEKz8mKyulJ4gm3Qdql/%F0%9F%AB%A7-%5BBLR%5D-The-B01LER?type=design&node-id=8035%3A7817&mode=design&t=eTH1Q2XmAvBy562Q-1) to new token naming documentation
- #357 should be done for this component in parallel

**Comment by larserbach** [comment]
@ChristianHoffmannS2 
Token renaming is almost done. There is the following issue to resolve:
```webpack 5.89.0 compiled with 3 warnings in 9364 ms
src/components/internal-components/form-caption-group/form-caption/index.ts:9:10 - error TS2305: Module '"./index.css"' has no exported member 'styleCustom'.```
The error results from the change on `form-caption/index.css` where I migrated the css from the foundation/semantic-tokens/forms.css
