### ISSUE TITLE
Counter - fix font color of neutral state and background color of warning and error state

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#578]
#### Description / User Story

In design the font color is defined as hsla(219, 10%, 40%, 1), in code it is currently hsla(220, 10%, 40%, 1). 

In figma the background color in error and warning state look different than in storybook.

This should be aligned.

----
#### Acceptance Criteria
- [x] Font colour of neutral state is same in code as in design
- [x] Background color for error and warning state is the same in code and design
- [x] Variant "default" has been renamed to "neutral" in storybook
- [x] In case props were changed: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

----
#### Background information
- This was found after #543  was done, therefor the errors are likely caused by semantic tokens and not by component tokens

**Comment by thrbnhrtmnn** [comment]
Hey @seemann , I saw that the first 2 ACs are already fixed on the current develop. The only open topic is the renaming of the default variant to "neutral". As you are also working on the radio issue, I would reassign this issue to @JpunktWpunkt, to fix the naming.

**Comment by JpunktWpunkt** [comment]
https://github.com/deven-org/B01LER-Kitchen/pull/826
