### ISSUE TITLE
FormLabel - fix font color and height

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#579]
#### Description / User Story

When comparing the component in Figma and in Storybook, it seems like the color and the sizing are not perfectly aligned. The color of the font in the light default variant in Figma is hsla(216, 10%, 10% 1), but in Storybook it is hsla(220, 10%, 10% 1). The height of the container in light & dark default SM is 17px in Figma but 16px in Storybook and for light & dark default LG it is 25px in Figma and 24 in Storybook. In the error variant the height is aligned in Figma and in Storybook for all sizes, variants and themes.

----
#### Acceptance Criteria
- [x] Font color for all light default FormLabels is aligned in Figma and Storybook
- [x] Height for all sizes in light and dark theme as well as default and error variant is aligned in Figma and Storybook
- [ ] In case props were changed: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

----
#### Background information
- Should we also check the behaviour for very long labels? Currently this seems to be handled differently in Figma and SB.
- Might already be solved with #545

**Comment by thrbnhrtmnn** [comment]
Hey @davidken91 , Hey @larserbach , I checked on the Form Label today and I saw that the colors are already correct. The only things missing are:
- In design there is no 8px bottom padding, this should probably be removed in code
- In design in dark mode MD default, the color of the label seems to be wrong (should probably be #FFFFFF, like in all other cases and in code).

**Comment by larserbach** [comment]
This is fixed:

> In design in dark mode MD default, the color of the label seems to be wrong (should probably be #FFFFFF, like in all other cases and in code).

**Comment by thrbnhrtmnn** [comment]
Hey @davidken91 , as I wrote yesterday, the color is already correct on develop and matches figma :-)
