### ISSUE TITLE
NumberInput - stepper buttons disappear when unit is undefined

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#675]
#### Step-by-Step Guide to reproduce

1. Open NumberInput in Storybook
2. Change unit to "undefined"
3. See how steppers will disappear

----
#### Bug Description / False Behaviour

When unit is undefined the steppers for the number input disappear.

----
#### Correct Behaviour

The stepper buttons in the number input are always there as defined, even when the unit is undefined.

----
#### Testing

_Check existing unit tests of the component(s) and adjust the tests to prevent this bug from occurring again in the future, if you see a way._

----
#### Background
- In case props were changed: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

**Comment by usmanreal1** [comment]
Hi,

I added a fix for this bug in another issue which is a copy of this:
#679

**Comment by thrbnhrtmnn** [comment]
Thanks for the contribution, issue is closed
