### ISSUE TITLE
NumberInput - placeholder can not be seen and stepper buttons appear in some cases

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#679]
#### Step-by-Step Guide to reproduce

1. Open NumberInput in Storybook
2. Look at component and see value 0 instead of placeholder message.
3. Change readonly to true or unit to undefined
4. See that stepper buttons are disappearing

----
#### Bug Description / False Behaviour

Currently the NumberInput value can not be undefined per default, making it not possible to see the placeholder per default. Also when changed to readonly or setting unit to undefined, the stepper buttons will disappear.

----
#### Correct Behaviour

The default NumberInput does not have a value, letting users see the placeholder message. Also the stepper buttons are still shown in the readonly state (and also when no unit is defined).

----
#### Testing

_Check existing unit tests of the component(s) and adjust the tests to prevent this bug from occurring again in the future, if you see a way._

----
#### Background
- In case props changed: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here
- ...

**Comment by usmanreal1** [comment]
Hi @thrbnhrtmnn ,

I created a PR for this issue since it was open and not assigned to anyone I just took it and added a fix.
Please let me know what you think about it and I would like to fix other issues as well.

https://github.com/deven-org/B01LER-Kitchen/pull/719

**Comment by thrbnhrtmnn** [comment]
Hey @usmanreal1 ,

thank you very much for the contribution! The team is currently taking a holiday break, we will have a look at your PR in the new year, once the team has returned 😊

FYI @larserbach , @ChristianHoffmannS2

**Comment by thrbnhrtmnn** [comment]
Issue was fixed with #719 , thank you for the contribution @usmanreal1
