### ISSUE TITLE
TextArea - fix scrolling

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#712]
#### Step-by-Step Guide to reproduce

The issue seems to only be happening in Firefox. On Chrome and Safari it is working as intended right now.

1. Navigate to https://b01ler.onrender.com/?path=/docs/design-system-web-components-forms-text-area--docs or https://b01ler.onrender.com/js-example-app
2. Find textarea
3. Ensure the Text Area is small enough, so scrolling will be enabled when enter some text (by reducing the size)
4. Start typing
5. See that once a few lines are filled with a value, the Text Area is scrolling up and down with every new input

https://github.com/deven-org/B01LER-Kitchen/assets/122102805/3a89146e-e67e-460e-9eac-78d51c915ebe

----
#### Bug Description / False Behaviour

TextArea scrolls up and down, when it should not.

----
#### Correct Behaviour

TextArea scroll as expected.

----
#### Testing

_Check existing unit tests of the component(s) and adjust the tests to prevent this bug from occurring again in the future, if you see a way._

----
#### Background
- ...

**Comment by thrbnhrtmnn** [comment]
Hey @larserbach , I created the issue, but I could not replicate the behaviour from the video, could you add more information about the issue to the description?

**Comment by JpunktWpunkt** [comment]
I searched for the error and found out: If I remove the key event on line 165 in the index.ts (@keyup=${this.updateCounter}) which update the counter, then it works well. Maybe this event could be adapted or like that?

**Comment by thrbnhrtmnn** [comment]
After merge we can move this to done as complete. No open topics from the design review.
