### ISSUE TITLE
Form Caption Group - change values for size prop

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#734]
#### Description / User Story

We should change values for the size prop, so different sizes actually have different values for the spacing in between the Form Caption / Slots.

This should be a rule, that B01LER always uses all variants / options of the props that we define and all variants should be build to have a function or look different.

Otherwise there will be a risk, that people report bugs for props that seem not to have a function.

----
#### Acceptance Criteria
- [x] Size prop in Form Caption Group has different values for SM, MD and LG
- [x] ~Remove sentence in Documentation (props panel description) that says the value is currently the same for all options)~ > will be updated in documentation with #704

----
#### Background information
- ...

**Comment by m-nti** [comment]
` Remove sentence in Documentation (props panel description) that says the value is currently the same for all options)

@thrbnhrtmnn 
is this for the devs? in Figma, there was no component description

**Comment by thrbnhrtmnn** [comment]
@m-nti , yes this is for the Storybook documentation.

**Comment by thrbnhrtmnn** [comment]
@m-nti , I think you can merge the changes and then we can close the issue :-)

**Comment by larserbach** [comment]
FigmaDesign is approved an merged

**Comment by thrbnhrtmnn** [comment]
Code changes need to be merged as well, then this issue can be closed @m-nti
