### ISSUE TITLE
Augment Semantic Tokens with ComponentTokens

### ISSUE THREAD

**Issue by larserbach** [deven-org/B01LER-Kitchen#784]
We might only want to component tokens on our components in Figma and Coded Comps.
This will make our system  more concise, reliable and maintainable.
Semantic token should remain, but be used as aliases only.

**Comment by thrbnhrtmnn** [comment]
As discussed today, we distanced us again from the approach described here. We might still want to do this in the future, but not now. Therefor this issue was closed.
