### ISSUE TITLE
Check for broken references in Figma

### ISSUE THREAD

**Issue by larserbach** [deven-org/B01LER-Kitchen#789]
When we are done with the renaming of all component tokens, we should check for:
- unresolved tokens (tokens studio inspect)
- components props with numeric values, which do not consume variables
- components props with color values, which do not consume variables
And fix all.

Subtasks:
- Identify issues and leave comment
- Fix issues (as I do not expect a lot of issues, this could be done in one PR)

**Comment by thrbnhrtmnn** [comment]
Done
