### ISSUE TITLE
Tooltip - offset not working after show code function fix

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#819]
#### Step-by-Step Guide to reproduce

1. Open Tooltip in Storybook
2. See that the offset is not as defined (4px per default)
3. Change the offset
4. See that the change is not there

----
#### Bug Description / False Behaviour

The offset of the tooltip is not working and does not change the offset between Tooltip Bubble and reference.

----
#### Correct Behaviour

The offset of the tooltip is working and does change the offset between Tooltip Bubble and reference.

----
#### Testing

_Check existing unit tests of the component(s) and adjust the tests to prevent this bug from occurring again in the future, if you see a way._

----
#### Background
- _Add more background information here, if needed._
- ...

**Comment by thrbnhrtmnn** [comment]
Hey @bar-tay , Christian informed me, that we have a general problem here and thus I created https://github.com/deven-org/B01LER-Kitchen/issues/829. I think we can close this issue as it will be solved with #829 . What do you think?

**Comment by bar-tay** [comment]
@thrbnhrtmnn sure.
